name: Documentation CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'docs/**'
      - '.github/workflows/docs-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Link Validation
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --no-progress docs/en/README.md docs/zh/README.md
          
      - name: Markdown Lint
        uses: avto-dev/markdown-lint@v2
        with:
          files: 'docs/**/*.md'
          config: '{"default": true, "line_length": false}'